name: Release Gradle Application

on:
  push:
    tags:
      - 'v*'  # Triggers when pushing tags like v1.0.0, v2.0.0, etc.

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use AdoptOpenJDK or others
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Application
        run: ./gradlew assembleDist

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "New release generated automatically."
          files: |
            build/distributions/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create And Publish Docker Image in ghcr
        env:
          RELEASE_TAG: ${{ github.ref_name }}
        id: publish image
        run: ./gradlew dockerPublishMainToGhcr
